# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(30, 10, 300, 80))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputlabel.setFont(font)
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputlabel.setObjectName("outputlabel")
        self.num7 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("7"))
        self.num7.setGeometry(QtCore.QRect(25, 110, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num7.setFont(font)
        self.num7.setObjectName("num7")
        self.divide = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("/"))
        self.divide.setGeometry(QtCore.QRect(268, 110, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.divide.setFont(font)
        self.divide.setObjectName("divide")
        self.num9 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("9"))
        self.num9.setGeometry(QtCore.QRect(189, 110, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num9.setFont(font)
        self.num9.setObjectName("num9")
        self.num8 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("8"))
        self.num8.setGeometry(QtCore.QRect(108, 110, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num8.setFont(font)
        self.num8.setObjectName("num8")
        self.num4 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("4"))
        self.num4.setGeometry(QtCore.QRect(25, 180, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num4.setFont(font)
        self.num4.setObjectName("num4")
        self.multiply = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("*"))
        self.multiply.setGeometry(QtCore.QRect(268, 180, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.num6 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("6"))
        self.num6.setGeometry(QtCore.QRect(189, 180, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num6.setFont(font)
        self.num6.setObjectName("num6")
        self.num5 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("5"))
        self.num5.setGeometry(QtCore.QRect(108, 180, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num5.setFont(font)
        self.num5.setObjectName("num5")
        self.num1 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("1"))
        self.num1.setGeometry(QtCore.QRect(25, 250, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num1.setFont(font)
        self.num1.setObjectName("num1")
        self.minus = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("-"))
        self.minus.setGeometry(QtCore.QRect(268, 250, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.num3 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("3"))
        self.num3.setGeometry(QtCore.QRect(189, 250, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num3.setFont(font)
        self.num3.setObjectName("num3")
        self.num2 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("2"))
        self.num2.setGeometry(QtCore.QRect(108, 250, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num2.setFont(font)
        self.num2.setObjectName("num2")
        self.equal = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.cal_it())
        self.equal.setGeometry(QtCore.QRect(25, 320, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.plus = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("+"))
        self.plus.setGeometry(QtCore.QRect(268, 320, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plus.setFont(font)
        self.plus.setObjectName("plus")
        self.dot = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.dot_it())
        self.dot.setGeometry(QtCore.QRect(189, 320, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dot.setFont(font)
        self.dot.setObjectName("dot")
        self.num0 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("0"))
        self.num0.setGeometry(QtCore.QRect(108, 320, 70, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.num0.setFont(font)
        self.num0.setObjectName("num0")
        self.ce = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("ce"))
        self.ce.setGeometry(QtCore.QRect(25, 390, 155, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ce.setFont(font)
        self.ce.setObjectName("ce")
        self.c = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("c"))
        self.c.setGeometry(QtCore.QRect(189, 390, 150, 60))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.c.setFont(font)
        self.c.setObjectName("c")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def clear_entry(self):
        if self.outputlabel.text() == "0":
            self.outputlabel.setText("")

    def cal_it(self):
        screen = self.outputlabel.text()
        answer = eval(screen)
        self.outputlabel.setText(str(answer))


    def dot_it(self):
        screen = self.outputlabel.text()
        if screen[-1] == ".":
            pass
        else:
            self.outputlabel.setText(f'{screen}.')

    def press_it(self, pressed):
        if pressed == "ce":
            self.outputlabel.setText("0")
        elif self.outputlabel.text() == "0":
            self. outputlabel.setText("")
        else:
            self.outputlabel.setText(f'{self.outputlabel.text()}{pressed}')



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Calculator"))
        self.outputlabel.setText(_translate("MainWindow", "0"))
        self.num7.setText(_translate("MainWindow", "7"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.num9.setText(_translate("MainWindow", "9"))
        self.num8.setText(_translate("MainWindow", "8"))
        self.num4.setText(_translate("MainWindow", "4"))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.num6.setText(_translate("MainWindow", "6"))
        self.num5.setText(_translate("MainWindow", "5"))
        self.num1.setText(_translate("MainWindow", "1"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.num3.setText(_translate("MainWindow", "3"))
        self.num2.setText(_translate("MainWindow", "2"))
        self.equal.setText(_translate("MainWindow", "="))
        self.plus.setText(_translate("MainWindow", "+"))
        self.dot.setText(_translate("MainWindow", "."))
        self.num0.setText(_translate("MainWindow", "0"))
        self.ce.setText(_translate("MainWindow", "CE"))
        self.c.setText(_translate("MainWindow", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
